"""initial

Revision ID: 15bebafcf3e0
Revises: 
Create Date: 2023-11-12 11:34:28.990990

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "15bebafcf3e0"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "template_read_model",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("info", sa.JSON(), nullable=False),
        sa.Column(
            "status",
            sa.Enum("NEW", "IN_PROGRESS", "COMPLETED", name="templatestatus"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("template_read_model")
    # ### end Alembic commands ###
